import type { Config } from "tailwindcss";
import { fontFamily } from "tailwindcss/defaultTheme";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
    },
    fontFamily: {
      heading: ["var(--font-sans)", ...fontFamily.serif],
      body: ["var(--font-sans)", ...fontFamily.sans],
    },
    extend: {
      colors: {
        primary: {
          100: "hsl(var(--primary-100) / <alpha-value>)",
          200: "hsl(var(--primary-200) / <alpha-value>)",
          300: "hsl(var(--primary-300) / <alpha-value>)",
          400: "hsl(var(--primary-400) / <alpha-value>)",
          500: "hsl(var(--primary-500) / <alpha-value>)",
          600: "hsl(var(--primary-600) / <alpha-value>)",
          700: "hsl(var(--primary-700) / <alpha-value>)",
          800: "hsl(var(--primary-800) / <alpha-value>)",
          900: "hsl(var(--primary-900) / <alpha-value>)",
        },
        accent: {
          100: "hsl(var(--accent-100) / <alpha-value>)",
          200: "hsl(var(--accent-200) / <alpha-value>)",
          300: "hsl(var(--accent-300) / <alpha-value>)",
          400: "hsl(var(--accent-400) / <alpha-value>)",
          500: "hsl(var(--accent-500) / <alpha-value>)",
          600: "hsl(var(--accent-600) / <alpha-value>)",
          700: "hsl(var(--accent-700) / <alpha-value>)",
          800: "hsl(var(--accent-800) / <alpha-value>)",
          900: "hsl(var(--accent-900) / <alpha-value>)",
        },
        tertiary: {
          100: "hsl(var(--tertiary-100) / <alpha-value>)",
          200: "hsl(var(--tertiary-200) / <alpha-value>)",
          300: "hsl(var(--tertiary-300) / <alpha-value>)",
          400: "hsl(var(--tertiary-400) / <alpha-value>)",
          500: "hsl(var(--tertiary-500) / <alpha-value>)",
          600: "hsl(var(--tertiary-600) / <alpha-value>)",
          700: "hsl(var(--tertiary-700) / <alpha-value>)",
          800: "hsl(var(--tertiary-800) / <alpha-value>)",
          900: "hsl(var(--tertiary-900) / <alpha-value>)",
        },
        green: {
          100: "hsl(var(--green-100) / <alpha-value>)",
          200: "hsl(var(--green-200) / <alpha-value>)",
          300: "hsl(var(--green-300) / <alpha-value>)",
          400: "hsl(var(--green-400) / <alpha-value>)",
          500: "hsl(var(--green-500) / <alpha-value>)",
          600: "hsl(var(--green-600) / <alpha-value>)",
          700: "hsl(var(--green-700) / <alpha-value>)",
          800: "hsl(var(--green-800) / <alpha-value>)",
          900: "hsl(var(--green-900) / <alpha-value>)",
        },
        blue: {
          100: "hsl(var(--blue-100) / <alpha-value>)",
          200: "hsl(var(--blue-200) / <alpha-value>)",
          300: "hsl(var(--blue-300) / <alpha-value>)",
          400: "hsl(var(--blue-400) / <alpha-value>)",
          500: "hsl(var(--blue-500) / <alpha-value>)",
          600: "hsl(var(--blue-600) / <alpha-value>)",
          700: "hsl(var(--blue-700) / <alpha-value>)",
          800: "hsl(var(--blue-800) / <alpha-value>)",
          900: "hsl(var(--blue-900) / <alpha-value>)",
        },
        yellow: {
          100: "hsl(var(--yellow-100) / <alpha-value>)",
          200: "hsl(var(--yellow-200) / <alpha-value>)",
          300: "hsl(var(--yellow-300) / <alpha-value>)",
          400: "hsl(var(--yellow-400) / <alpha-value>)",
          500: "hsl(var(--yellow-500) / <alpha-value>)",
          600: "hsl(var(--yellow-600) / <alpha-value>)",
          700: "hsl(var(--yellow-700) / <alpha-value>)",
          800: "hsl(var(--yellow-800) / <alpha-value>)",
          900: "hsl(var(--yellow-900) / <alpha-value>)",
        },
        pink: {
          100: "hsl(var(--pink-100) / <alpha-value>)",
          200: "hsl(var(--pink-200) / <alpha-value>)",
          300: "hsl(var(--pink-300) / <alpha-value>)",
          400: "hsl(var(--pink-400) / <alpha-value>)",
          500: "hsl(var(--pink-500) / <alpha-value>)",
          600: "hsl(var(--pink-600) / <alpha-value>)",
          700: "hsl(var(--pink-700) / <alpha-value>)",
          800: "hsl(var(--pink-800) / <alpha-value>)",
          900: "hsl(var(--pink-900) / <alpha-value>)",
        },
        purple: {
          100: "hsl(var(--purple-100) / <alpha-value>)",
          200: "hsl(var(--purple-200) / <alpha-value>)",
          300: "hsl(var(--purple-300) / <alpha-value>)",
          400: "hsl(var(--purple-400) / <alpha-value>)",
          500: "hsl(var(--purple-500) / <alpha-value>)",
          600: "hsl(var(--purple-600) / <alpha-value>)",
          700: "hsl(var(--purple-700) / <alpha-value>)",
          800: "hsl(var(--purple-800) / <alpha-value>)",
          900: "hsl(var(--purple-900) / <alpha-value>)",
        },
        gray: {
          500: "hsl(var(--gray-500) / <alpha-value>)",
          400: "hsl(var(--gray-400) / <alpha-value>)",
          300: "hsl(var(--gray-300) / <alpha-value>)",
          200: "hsl(var(--gray-200) / <alpha-value>)",
          150: "hsl(var(--gray-150) / <alpha-value>)",
          50: "hsl(var(--gray-50) / <alpha-value>)",
          35: "hsl(var(--gray-35) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
